[build]
image_path = "target/kernel.iso"

[qemu]
binary = "qemu-system-x86_64"
base_args = [
    # Memory
    "-m", "4G",

    # SMP settings
    "-smp", "2", 
    "-cpu", "Conroe-v1,+x2apic,+invtsc",

    # Network
    "-netdev", "user,id=net0",
    "-device", "virtio-net-pci,netdev=net0",

    # Audio
    "-device", "intel-hda",
    "-device", "hda-duplex",

    # General Storage
    "-drive", "id=mysdcard,file=storage_test.img,if=none,format=raw",
    "-device", "sdhci-pci",
    "-device", "sd-card,drive=mysdcard", 

    # Graphics
    "-vga", "std",

    # Boot media and UEFI settings
    "-cdrom", "{image}",
    "-drive", "if=pflash,unit=0,format=raw,file={ovmf}/ovmf-code-x86_64.fd,readonly=on",
    "-drive", "if=pflash,unit=1,format=raw,file={ovmf}/ovmf-vars-x86_64.fd"
]

[modes]
terminal = { args = ["-nographic"] }
gui = { args = [] }
gdb-terminal = { args = ["-nographic", "-s", "-S"] }
gdb-gui = { args = ["-s", "-S"] }

[test]
timeout_secs = 20
success_exit_code = 33
no_reboot = true
extra_args = [
    "-device", "isa-debug-exit,iobase=0xf4,iosize=0x04",
    "-serial", "stdio",
    "-display", "none"
]